name: リンク切れチェック

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, reopened, synchronize]

# プルリクエストで起動するワークフローは、最新コード以外での実行がたいてい不要です。
# 自動テストや静的解析はその典型で、古いコードで実行されるワークフローはムダです。
# そこで次のように実装し、古いワークフローは自動キャンセルしましょう。
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read # コードの読み込みを許可

    # =============================
    # 環境変数の設定
    # - イベントタイプに応じて異なるソースから値を取得
    # - 必要に応じてデフォルト値を設定
    # =============================
    env:
      # 対象リポジトリ（ブランド）名の決定ロジック
      HOST: vars.DEVELOPMENT_HOST
      PORT: vars.DEVELOPMENT_PORT
      USER_NAME: vars.DEVELOPMENT_USER_NAME
      LOCAL_PATH: ${{ vars.LOCAL_PATH }}${{ github.event.repository.name }}
      REMOTE_PATH: ${{ vars.DEVELOPMENT_REMOTE_PATH }}${{ github.event.repository.name }}
      SYNC_MODE: "delta"

      TARGET_REPOSITORY: ${{ github.event.repository.name }}

      TARGET_ENVIRONMENT: "検証環境"

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Node.jsセットアップ
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v3.5.1
        with:
          node-version: 'latest'

      - name: Cache npm dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Cache http-server output
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ./.http-server-cache
          key: ${{ runner.os }}-http-server-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-http-server-

      - name: Create cache directory if it doesn't exist
        run: mkdir -p ./.http-server-cache

      - name: Start local server
        run: |
          npx http-server ./public -p 8081 --cache ./.http-server-cache &
          sleep 5

      - name: Run link checker
        id: link-checker
        run: node link-checker.js

      - name: Post broken links to PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const errorsArray = ${{ steps.link-checker.outputs.errors }}

            let message = "";
            for (let key in errorsArray) {
              for (let i = 0, len = errorsArray[key].length; i < len; i++) {
                message += `| ${key} | ${errorsArray[key][i]} |\n`;
              }
            }

            const comment = `
              ## Broken Links Report
              | ファイル名 | リンク切れパス |
              | :-- | :-- |
              ${message}
            `;
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: comment
            });
