name: リンク切れチェック

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, reopened, synchronize]

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.jsセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 依存関係のインストール
        run: |
          npm install broken-link-checker
          npm install @actions/core @actions/github

      - name: リンクチェック実行
        id: link-check
        run: node ./.github/actions/check-links.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
