name: リンク切れチェック

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, reopened, synchronize]

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Node.jsセットアップ
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v3.5.1
        with:
          node-version: 'latest'

      - name: 依存関係のインストール
        run: |
          npm install broken-link-checker
          npm install @actions/core @actions/github

      - name: リンクチェック実行
        id: link-check
        run: node ./.github/actions/check-links.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
