name: PageSpeed Insights Check
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]

jobs:
  extract-html-diff:
    runs-on: ubuntu-latest
    outputs:
      html_files: ${{ steps.set_output.outputs.html_files }}
      html_count: ${{ steps.set_output.outputs.html_count }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract HTML file differences
        id: extract_diff
        run: |
          # mainブランチとの差分から.htmlファイルだけを抽出
          # HTML_FILES=$(git diff --name-only origin/main HEAD | grep 'public/\.*\.html$' | tr '\n' ',' || echo "")
          # HTML_FILES=$(git diff --name-only origin/main HEAD | grep 'public/.*\.html$' | tr '\n' ',' || echo "")
          HTML_FILES=$(git diff --name-only origin/main HEAD | grep 'public/.*\.html$' | sed 's#public/##g' | tr '\n' ',' || echo "")

          # 結果を出力
          if [ -z "$HTML_FILES" ]; then
            echo "No HTML files changed"
          else
            echo "HTML files changed:"
            echo "$HTML_FILES"
          fi

          # 変更があったHTMLファイルの数をカウント
          HTML_COUNT=$(echo "$HTML_FILES" | grep -v '^$' | wc -l)

          # 次のステップで使用するために一時ファイルに保存
          echo "$HTML_FILES" > /tmp/html_files.txt
          echo "$HTML_COUNT" > /tmp/html_count.txt

      - name: Set output values
        id: set_output
        run: |
          HTML_FILES=$(cat /tmp/html_files.txt)
          HTML_COUNT=$(cat /tmp/html_count.txt)

          # マルチラインの出力を適切にエスケープ
          HTML_FILES_ESCAPED="${HTML_FILES//'%'/'%25'}"
          HTML_FILES_ESCAPED="${HTML_FILES_ESCAPED//$'\n'/'%0A'}"
          HTML_FILES_ESCAPED="${HTML_FILES_ESCAPED//$'\r'/'%0D'}"

          echo "html_files=$HTML_FILES_ESCAPED" >> $GITHUB_OUTPUT
          echo "html_count=$HTML_COUNT" >> $GITHUB_OUTPUT

  check_psi:
    needs: extract-html-diff
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ needs.extract-html-diff.outputs.html_count > 0 }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check PSI
        env:
          PSI_API_KEY: ${{ secrets.PSI_API_KEY }}
          HTML_FILES: ${{ needs.extract-html-diff.outputs.html_files }}
          # SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          # SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        id: psi_check
        run: |
          echo "HTML_FILES: ${{ needs.extract-html-diff.outputs.html_files }}"
          RESULT=$(node .github/actions/psi)
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$RESULT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR with PSI results
        uses: actions/github-script@v7.0.1
        if: ${{ steps.psi_check.outcome == 'success' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = `${{ steps.psi_check.outputs.result }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ⚡️ PageSpeed Insights Results\n\n${result}`
            });
